# Generated by Django 5.2.4 on 2025-10-14 15:55

from django.db import migrations, models
from datetime import date


def set_created_at_field(apps, schema_editor):
    """Date field was sometimes used as created_at field, implying incorrect date ranges."""
    Indicator = apps.get_model("core", "Indicator")

    for indicator in Indicator.objects.all():
        try:
            creation_date = indicator.date
        except ValueError:
            creation_date = date.today()
        indicator.created_at = creation_date
        indicator.updated_at = creation_date
        indicator.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_product_dataset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="date and time at which a record was created",
                null=True,
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="date and time at which a record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.RunPython(
            set_created_at_field, reverse_code=migrations.RunPython.noop
        ),
    ]
